name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Simple file check
      run: |
        echo "Checking for required files..."
        ls -la
        echo "✅ Repository contents verified"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "🚀 Starting deployment..."
          
          # Create deployment script
          mkdir -p ~/scripts
          cd ~/scripts
          
          cat > simple-deploy.sh << 'DEPLOY_EOF'
          #!/bin/bash
          echo "Deploying website..."
          
          # Get latest code
          cd /tmp
          rm -rf my-devops-journey
          git clone https://github.com/Evelynval-w/my-devops-journey.git
          cd my-devops-journey
          
          # Deploy files
          sudo cp *.html /var/www/html/ 2>/dev/null || echo "No HTML files"
          sudo cp *.css /var/www/html/ 2>/dev/null || echo "No CSS files" 
          sudo cp *.js /var/www/html/ 2>/dev/null || echo "No JS files"
          
          # Fix permissions
          sudo chown -R apache:apache /var/www/html/
          sudo chmod -R 644 /var/www/html/*
          
          # Restart web server
          sudo systemctl restart httpd
          
          echo "✅ Deployment complete!"
          DEPLOY_EOF
          
          chmod +x simple-deploy.sh
          ./simple-deploy.sh
          
          # Quick verification
          sleep 2
          if curl -s localhost | grep -q "DevOps"; then
            echo "✅ Website deployed successfully!"
          else
            echo "⚠️  Website deployed but verification unclear"
          fi
